#!/usr/bin/env bash
# The offline gate. Runs against a tarball or an unpacked bundle, needs no network, no
# toolchain, and no checkout - a stranger who downloaded one file can run it on what they got.
#
#   scripts/release/verify-sdk-bundle.sh <orbis-sdk-v.tar.gz | unpacked-dir>
#
# A copy of this script ships INSIDE every bundle as ./verify.sh, so the check travels with
# the thing it checks.
#
# WHAT IT CHECKS, in the order it checks it:
#   1. every file matches its sha256 in SHA256SUMS, and no file is present that SHA256SUMS
#      does not account for (an EXTRA file is drift too - it means something was added by hand)
#   2. every component in the licence table has its licence text present and non-trivial
#   3. NOTICE.md is not stale relative to that table
#   4. the Mesa half and the orbis-compat half are a coherent pair - the same commit, or two
#      commits across which include/ is byte-identical, which is all Mesa compiles from here
#  4b. the include/ tree in this bundle is the one Mesa compiled - recomputed here and compared
#      against the fingerprint mesa/manifest.txt recorded on the machine that ran the compiler.
#      This is check 4 done rather than believed; a Mesa manifest predating that field leaves it
#      NOT CHECKED (rc=4), never silently passed
#   5. every symbol the Mesa archives import from orbis-compat is still defined by the
#      orbis-compat in the bundle - IF a symbol reader is available (see below)
#   6. the layout is the one the toolchain file and every consumer's build reads
#
# ⚠ WHAT IT PROVABLY CANNOT CHECK, and this list is the honest half of the gate:
#
#   * THAT THE BUNDLE BUILDS ANYTHING. Nothing here compiles or links. bundle-gate.sh is that
#     check and it is a separate script for exactly that reason.
#   * MEANING, ONLY PRESENCE. Check 5 is the same assertion the three sibling repositories
#     carry and inherits its stated limit verbatim: "presence, not meaning. Constants inlined
#     at Mesa's compile time leave no symbol to check at all." A struct that changed size, a
#     macro that changed value, a `sigevent` whose fields moved - none of those move a symbol
#     name and none of them fail check 5. Check 4 is what actually covers that class, and it
#     covers it by refusing the combination rather than by inspecting it.
#   * THAT A LICENCE IS THE RIGHT ONE. Check 2 proves a file of that name is present and
#     matches its hash. It cannot prove that FTL.TXT is the licence FreeType's headers in this
#     particular tarball were released under, or that llvmorg-11.0.0's libcxx/LICENSE.TXT is
#     the right text for these libc++ objects. Those are judgements, they are argued in
#     LICENSING.md with the measurements behind them, and a script cannot re-make them.
#   * THAT sdk/lib/*.so MAY BE REDISTRIBUTED AT ALL. ~422 generated import stubs whose
#     generator and whose input data are both archived with no LICENSE file. There is nothing
#     to check them against. NOTICE.md says so; this script cannot improve on that.
#   * THAT THE BUNDLE IS THE ONE UPSTREAM PUBLISHED. SHA256SUMS is generated by the same run
#     that wrote the files. It detects corruption and tampering AFTER the cut, not a
#     compromised cut. The tarball's own .sha256, published separately, is what covers that.
#
# Exit codes: 0 ok · 1 the bundle FAILED a check · 2 usage · 4 INCOMPLETE (a check could not
# be run on this host, so it proves nothing - and that is reported, never silently skipped).
set -euo pipefail

TARGET="${1:-}"
[ -n "$TARGET" ] || { echo "usage: $0 <bundle.tar.gz | unpacked-bundle-dir>" >&2; exit 2; }

log(){  printf '\033[1;34m==>\033[0m %s\n' "$*"; }
ok(){   printf '   \033[1;32mok\033[0m   %s\n' "$*"; }
warn(){ printf '\033[1;33m!!\033[0m %s\n' "$*" >&2; }
err(){  printf '\033[1;31mXX\033[0m %s\n' "$*" >&2; }
_sha256c(){ if command -v sha256sum >/dev/null 2>&1; then sha256sum -c --quiet -; else shasum -a 256 -c --quiet -; fi; }
_sha256(){ if command -v sha256sum >/dev/null 2>&1; then sha256sum "$@"; else shasum -a 256 "$@"; fi; }
_size(){ if stat -c%s "$1" >/dev/null 2>&1; then stat -c%s "$1"; else stat -f%z "$1"; fi; }

# ⚠ A COPY. The definition, with the reasoning, is make-sdk-bundle.sh's _include_sha256; mesa-ps4's
# release.yml carries the third. The three numbers are compared for EQUALITY across three machines
# that cannot share a file, so a "tidy-up" here that changes one byte of output reads downstream as
# a mismatched pair and refuses a bundle that is fine. Change all three in one commit or none.
_include_sha256(){
  ( cd "$1" && find include -type f -print0 | LC_ALL=C sort -z \
      | while IFS= read -r -d '' f; do _sha256 "$f"; done | _sha256 | cut -d' ' -f1 )
}

RC=0
INCOMPLETE=0
CLEANUP=""
trap '[ -n "$CLEANUP" ] && rm -rf "$CLEANUP"' EXIT

if [ -f "$TARGET" ]; then
  CLEANUP="$(mktemp -d)"
  log "unpacking $(basename "$TARGET")"
  tar -xzf "$TARGET" -C "$CLEANUP"
  B="$(dirname "$(find "$CLEANUP" -maxdepth 2 -name BUNDLE.txt -print -quit)")"
  [ -n "$B" ] && [ "$B" != "." ] || { err "no BUNDLE.txt anywhere in $TARGET"; exit 1; }
elif [ -d "$TARGET" ]; then
  B="$(cd "$TARGET" && pwd -P)"
else
  err "$TARGET is neither a file nor a directory"; exit 2
fi
[ -f "$B/BUNDLE.txt" ] || { err "$B has no BUNDLE.txt - not an orbis-sdk bundle"; exit 1; }

field(){ sed -n "s/^$1=//p" "$B/BUNDLE.txt" | head -1; }
# mesa/manifest.txt is the PRIMARY record for anything about the Mesa half: BUNDLE.txt's copies of
# those fields were written from it, so they are a transcription, not a second witness.
# ⚠ THE -f GUARD IS NOT DECORATION. `sed missing-file 2>/dev/null | head -1` exits 2, pipefail
# hands that to the assignment, and set -e ends the whole run there - so a bundle with no
# mesa/manifest.txt died at rc=2 printing nothing, instead of reaching check 4's message that says
# exactly what is wrong with it. Returning empty is what lets the checks below report it.
mesa_field(){ [ -f "$B/mesa/manifest.txt" ] || return 0; sed -n "s/^$1=//p" "$B/mesa/manifest.txt" | head -1; }
log "$(field bundle) - built $(field built) by $(field built-by)"

# -----------------------------------------------------------------------------------------
# 1. sha256 over everything, both directions.
# -----------------------------------------------------------------------------------------
log "1. every file vs SHA256SUMS"
if [ ! -f "$B/SHA256SUMS" ]; then
  err "no SHA256SUMS - a bundle that cannot say what it contains is not verifiable"; RC=1
else
  if ( cd "$B" && _sha256c < SHA256SUMS ); then
    ok "$(grep -c . "$B/SHA256SUMS") files match"
  else
    err "a file does not match its recorded sha256 (named above)"; RC=1
  fi
  extra="$(comm -23 \
    <(cd "$B" && find . -type f ! -name SHA256SUMS | LC_ALL=C sort) \
    <(awk '{sub(/^[^ ]+  /,""); print}' "$B/SHA256SUMS" | LC_ALL=C sort) || true)"
  if [ -n "$extra" ]; then
    err "file(s) present that SHA256SUMS does not account for:"
    printf '     %s\n' $extra; RC=1
  else
    ok "no unaccounted files"
  fi
fi

# -----------------------------------------------------------------------------------------
# 2 + 3. The licence ledger, run from the copy inside the bundle so it checks the bundle's
#        own licenses/ and NOTICE.md rather than some checkout's.
# -----------------------------------------------------------------------------------------
log "2+3. licence texts present, and NOTICE.md not stale"
if [ -x "$B/toolchain/sdk-licenses.sh" ] && [ -d "$B/licenses" ] && [ -f "$B/NOTICE.md" ]; then
  # sdk-licenses.sh resolves licenses/ and NOTICE.md relative to its own ../.. - which inside
  # the bundle is the bundle root. That is why it ships at toolchain/, one level down.
  if "$B/toolchain/sdk-licenses.sh" verify; then ok "licence ledger verifies"
  else err "the licence ledger does not verify"; RC=1; fi
else
  err "the bundle carries no licence ledger (toolchain/sdk-licenses.sh + licenses/ + NOTICE.md)"; RC=1
fi

# -----------------------------------------------------------------------------------------
# 4. THE PAIRING. The one check a bundle exists to make possible.
# -----------------------------------------------------------------------------------------
log "4. Mesa and orbis-compat are the same pair"
PAIRING="$(field pairing)"
COMPAT_SHA="$(field orbis-compat-commit)"
MESA_AGAINST="$(field mesa-built-against-orbis-compat)"
MESA_MANIFEST_AGAINST="$(mesa_field orbis-compat-commit)"
BASIS="$(field pairing-basis)"
printf '   orbis-compat shipped        %s\n' "${COMPAT_SHA:0:12}"
printf '   Mesa built against          %s  (BUNDLE.txt)\n' "${MESA_AGAINST:0:12}"
printf '   Mesa built against          %s  (mesa/manifest.txt, the primary record)\n' "${MESA_MANIFEST_AGAINST:0:12}"
if [ -z "$MESA_MANIFEST_AGAINST" ]; then
  err "mesa/manifest.txt records no orbis-compat-commit. The pairing cannot be checked at all,
   and BUNDLE.txt's copy is not independent evidence - it was written from that same file."
  RC=1
elif [ "$MESA_AGAINST" != "$MESA_MANIFEST_AGAINST" ]; then
  err "BUNDLE.txt and mesa/manifest.txt disagree about which orbis-compat Mesa saw.
   One of them was edited after the cut."
  RC=1
elif [ "$COMPAT_SHA" != "$MESA_MANIFEST_AGAINST" ] \
     && [ "$BASIS" != include-identical ] && [ "$BASIS" != include-sha-match ]; then
  err "MISMATCHED PAIR. Mesa compiled against ${MESA_MANIFEST_AGAINST:0:12} and this bundle ships
   ${COMPAT_SHA:0:12}. The import-list check below does NOT cover this: it tests that names
   still exist, and a struct that changed size does not change a name. Do not publish."
  RC=1
elif [ "$COMPAT_SHA" != "$MESA_MANIFEST_AGAINST" ]; then
  # ⚠ THE COMMITS DIFFER AND THE HEADERS DID NOT. include/ is the whole of what Mesa compiles from
  # this repository, so a bundle whose commits differ while include/ is identical is coherent -
  # measured 2026-09-17, a bundle was refused over cc75949..4f61d6f, three commits whose
  # `git diff -- include/` is empty. The commit ids stay in BUNDLE.txt as provenance; they are not
  # the test. What the cut recorded as its basis is repeated here, and check 4b is where the claim
  # is actually settled - by numbers, not by this line.
  warn "commits differ (${MESA_MANIFEST_AGAINST:0:12} vs ${COMPAT_SHA:0:12}); the cut recorded"
  warn "  pairing-basis=$BASIS. See 4b for what was proven about the headers themselves."
elif [ "$PAIRING" != "ok" ]; then
  err "BUNDLE.txt says pairing=$PAIRING. It was cut with --allow-pair-mismatch."
  RC=1
else
  ok "same pair: ${COMPAT_SHA:0:12}"
fi
if [ "$(field orbis-compat-dirty)" = yes ]; then
  # ⚠ INCOMPLETE, NOT FAILED, AND THE DIFFERENCE IS WHAT LETS THE GATE RUN AT ALL. A dirty
  # bundle is unpublishable - the commit in BUNDLE.txt does not describe its bytes, so nobody
  # can reproduce it - but it is not BROKEN: every file still matches SHA256SUMS, the pair is
  # still consistent, and it can be built from. Those are different verdicts.
  #
  # As RC=1 this was a deadlock, found on the first real run. bundle-gate.sh runs this script
  # as a precondition and tolerates rc=4 (INCOMPLETE) precisely because gate=unproven is the
  # state it exists to fix - but rc=1 made it refuse, so a bundle cut from a working tree could
  # never reach the gate, and the gate is the only thing that can turn gate=unproven into
  # gate=pass. Development bundles are cut dirty by definition; a gate that only runs on an
  # already-clean tree is a gate that never runs while the work is being done.
  #
  # Nothing is loosened: INCOMPLETE still refuses publication, BUNDLE.txt still records the
  # dirt, and the final tarball has to be re-cut from a committed tree to come back OK.
  warn "orbis-compat-dirty=yes: the commit in BUNDLE.txt does not describe the bytes shipped."
  warn "  Buildable and gateable, but NOT publishable. Re-cut from a committed tree."
  INCOMPLETE=1
fi

# -----------------------------------------------------------------------------------------
# 4b. THE FINGERPRINT - check 4 DONE rather than believed.
#
# ⚠ THIS USED TO BE THE WEAKEST LINE IN THE SCRIPT. Until mesa-ps4 recorded it, the only number
# available was the cut's own: this script recomputed include/ and compared it against
# BUNDLE.txt's orbis-compat-include-sha256, which proved the headers were not altered AFTER the
# cut and nothing whatever about what Mesa compiled. "The commits differ but include/ is
# identical" was a verdict reached elsewhere, with a git history a stranger does not have, and
# read back out of a file written by the same run that reached it. One number, read twice.
#
# mesa/manifest.txt now carries orbis-compat-include-sha256 too, measured on the runner that ran
# the compiler, by the same _include_sha256. So there are two independently produced numbers and a
# third recomputed here from the bytes on disk, and agreement between them is evidence rather than
# testimony. Equality is the whole test: see _include_sha256's comment on why all three copies of
# it must stay byte-identical.
#
# ⚠ AN OLDER MESA MANIFEST IS "NOT CHECKED", NOT "FAILED". Every Mesa bundle published before
# 2026-09-18 predates the field, and a bundle built from one is not thereby broken - it is
# unproven, which is the same verdict this script gives a host with no llvm-nm and a bundle with
# gate=unproven. It exits 4, it says which half went unchecked, and it does not silently pass.
log "4b. include/ in this bundle is the tree Mesa compiled"
INC_GOT="$(_include_sha256 "$B/orbis-compat")"
INC_CUT="$(field orbis-compat-include-sha256)"
INC_MESA="$(mesa_field orbis-compat-include-sha256)"
INC_CUT_SAYS_MESA="$(field mesa-built-against-include-sha256)"
printf '   include/ recomputed here    %s\n' "${INC_GOT:0:12}"
printf '   recorded at the cut         %s  (BUNDLE.txt)\n' \
  "$( [ -n "$INC_CUT" ] && echo "${INC_CUT:0:12}" || echo "unrecorded   " )"
printf '   recorded by the Mesa build  %s  (mesa/manifest.txt, the primary record)\n' \
  "$( [ -n "$INC_MESA" ] && echo "${INC_MESA:0:12}" || echo "unrecorded   " )"

if [ -z "$INC_CUT" ]; then
  warn "no orbis-compat-include-sha256 in BUNDLE.txt - cut by a script older than the field."
  warn "  Nothing here can show whether the headers were altered AFTER the cut; the Mesa"
  warn "  comparison below is a separate question and still stands. NOT CHECKED."
  INCOMPLETE=1
elif [ "$INC_CUT" = "$INC_GOT" ]; then
  ok "include/ matches the fingerprint taken at the cut (${INC_GOT:0:12})"
else
  err "include/ does not match the fingerprint in BUNDLE.txt - the headers were altered after
   the cut. want ${INC_CUT:0:12}, got ${INC_GOT:0:12}"
  RC=1
fi

# ⚠ CHECKED BEFORE THE ABSENCE TEST, because an empty field in the manifest while BUNDLE.txt names
# a hash is not an old manifest - it is a manifest somebody stripped after the cut, and it must not
# be able to buy itself the lenient branch below. It runs in the other direction too: the cut
# writes `unrecorded` when the Mesa bundle had no such field, so `unrecorded` here beside a hash
# there means the manifest GREW one after the cut. Same shape as the commit disagreement in check
# 4, and "" in BOTH is the genuinely old bundle that lands on the lenient branch.
# ⚠ `[ x ] && y=` WOULD KILL THE SCRIPT HERE: under set -e a false test is the last status of the
# list, at the top level, and the run ends at rc=1 with no message. Written as an if.
_cut_says="$INC_CUT_SAYS_MESA"
if [ "$_cut_says" = unrecorded ]; then _cut_says=""; fi
if [ -n "$INC_CUT_SAYS_MESA" ] && [ "$_cut_says" != "$INC_MESA" ]; then
  err "BUNDLE.txt and mesa/manifest.txt disagree about the include/ tree Mesa compiled:
   ${INC_CUT_SAYS_MESA:0:12} vs ${INC_MESA:-<absent>}. One of them was edited after the cut."
  RC=1
elif [ -z "$INC_MESA" ] || [ "$INC_MESA" = unrecorded ]; then
  warn "mesa/manifest.txt records no orbis-compat-include-sha256 - this Mesa bundle predates the"
  warn "  field. What Mesa compiled is a RECORDED verdict carried from the cut, NOT re-derived"
  warn "  here. Rebuild Mesa to get the half of check 4 that cannot be faked. NOT CHECKED."
  INCOMPLETE=1
elif [ "$INC_MESA" = "$INC_GOT" ]; then
  ok "Mesa's own record of the headers it compiled IS the include/ in this bundle (${INC_GOT:0:12})"
elif [ "$INC_MESA" = "$INC_CUT" ]; then
  # Both recorded numbers agree with each other and neither matches the bytes: the tarball's
  # include/ was replaced after the cut, and the check above has already failed on it. Say which
  # of the three disagrees rather than repeating "mismatch".
  err "the two recorded fingerprints agree (${INC_MESA:0:12}) and the include/ in this bundle is
   ${INC_GOT:0:12}. The headers here are neither what Mesa compiled nor what was cut."
  RC=1
else
  err "MISMATCHED PAIR, MEASURED. Mesa compiled include/ ${INC_MESA:0:12} and this bundle ships
   ${INC_GOT:0:12}. This is not a commit-id disagreement that a diff can excuse - the header
   BYTES differ. A struct that changed size does not change a symbol name, so check 5 below
   will pass anyway and the title will fail at run time. Do not publish."
  RC=1
fi

# -----------------------------------------------------------------------------------------
# 5. The import list. Best effort: it needs a symbol reader, and a bundle is verifiable
#    WITHOUT one - so a missing llvm-nm makes the run INCOMPLETE, not failed.
# -----------------------------------------------------------------------------------------
log "5. Mesa's imports are still defined by the bundle's orbis-compat"
NM=""
for c in llvm-nm nm; do command -v "$c" >/dev/null 2>&1 && { NM="$c"; break; }; done
LIB="$B/orbis-compat/build/liborbis-compat.a"
want="$(mktemp)"; have="$(mktemp)"
sed -n '/^\[orbis-compat-imports\]/,$p' "$B/BUNDLE.txt" | tail -n +2 \
  | sed '/^[[:space:]]*$/d;/^#/d' | LC_ALL=C sort -u > "$want"
if [ ! -s "$want" ]; then
  err "BUNDLE.txt records no orbis-compat imports at all. Mesa's archives are known to import
   at least orbis_sysconf - orbis-compat's <unistd.h> makes sysconf a macro for it - so an
   empty list means the measurement failed, not that the coupling is gone."
  RC=1
elif [ -z "$NM" ]; then
  warn "no llvm-nm or nm on this host - check 5 NOT RUN. This says nothing about the bundle."
  warn "  $(wc -l < "$want" | tr -d ' ') names were recorded and went unchecked."
  INCOMPLETE=1
elif [ ! -f "$LIB" ]; then
  err "no $LIB - the bundle has no archive to check the imports against"; RC=1
else
  # ⚠ Apple's nm and LLVM's print different columns. Both put the type letter second-to-last
  # and the name last for a defined symbol, which is what this relies on.
  #
  # ⚠ NO `sed 's/^_//'` HERE, AND ITS REMOVAL IS THE FIRST THING A REAL RUN OF THIS SCRIPT
  # FOUND. It was there for Mach-O's leading-underscore convention, and on an ELF archive it
  # silently truncates every Itanium-ABI C++ name, all of which begin `_Z`:
  #
  #     _Znam                 -> Znam
  #     _Znwm                 -> Znwm
  #     _ZnwmRKSt9nothrow_t   -> ZnwmRKSt9nothrow_t
  #
  # The wanted list out of BUNDLE.txt is NOT stripped, so those three could never match, and
  # the check failed naming exactly the three symbols the archive does define as `T`. Measured
  # 2026-09-17 against orbis-compat 44934e4 and orbis-mesa-a4fa6b57f8bd: operator new and
  # operator new[] are imported by libvulkan_radeon.a, libEGL.a and libgallium, so this was not
  # an edge case - it was every C++ import in the bundle.
  #
  # ⚠ AND THE STRIP WOULD HAVE FAILED ON LINUX TOO. llvm-nm is first on the PATH in CI, so this
  # is not a macOS bug that CI would have caught; the check has never passed with a C++ name in
  # the list on any host. The archive is ELF whichever nm reads it, and ELF carries no
  # underscore prefix, so there is nothing here to strip.
  "$NM" --defined-only "$LIB" 2>/dev/null \
    | awk 'NF>=2 && ($(NF-1)=="T"||$(NF-1)=="W"||$(NF-1)=="D"||$(NF-1)=="B"||$(NF-1)=="t"){print $NF}' \
    | LC_ALL=C sort -u > "$have"
  missing="$(LC_ALL=C comm -23 "$want" "$have" || true)"
  if [ -n "$missing" ]; then
    err "orbis-compat ${COMPAT_SHA:0:12} does not define names the bundle's Mesa imports:"
    printf '     %s\n' $missing
    err "  Mesa cannot link against this. (Read with: $NM)"
    RC=1
  else
    ok "all $(wc -l < "$want" | tr -d ' ') imports satisfied by $(basename "$LIB") (read with $NM)"
  fi
fi
rm -f "$want" "$have"

# -----------------------------------------------------------------------------------------
# 6. The layout. Cheap, and it is what turns "the tarball unpacked" into "a build will find
#    what it reaches for". Every path below is one a consumer's build actually reads.
# -----------------------------------------------------------------------------------------
log "6. the layout a consumer's build reads"
need_file(){ [ -f "$B/$1" ] && ok "$1" || { err "MISSING $1 - $2"; RC=1; }; }
need_dir(){  [ -d "$B/$1" ] && ok "$1/" || { err "MISSING $1/ - $2"; RC=1; }; }
need_file toolchain/orbis-sdk.cmake "the one file a consumer points CMake at"
need_file toolchain/orbis-tls.ld    "the corrected linker script; GPL-3.0-only, see NOTICE.md"
need_file toolchain/orbis.ini.in    "the meson cross file template env.sh materialises"
need_file env.sh                    "the four variables, for meson/make consumers"
need_file sdk/link.x                "orbis-env.sh and ps4-openorbis.cmake both probe for this"
need_file sdk/lib/libc.a            "without it the sdk/ directory is a source stash, not an SDK"
need_file sdk/lib/crt1.o            "the entry object every link names last"
need_dir  sdk/include/orbis         "the platform headers"
need_dir  sdk/include/c++/v1        "libc++, and it must be searched ahead of the C headers"
need_file orbis-compat/cmake/ps4-openorbis.cmake "the real toolchain file; orbis-sdk.cmake includes it"
need_file orbis-compat/cmake/orbis-compat.cmake  "orbis_compat_locate/target/verify"
need_file orbis-compat/build/liborbis-compat.a   "the archive, linked with --whole-archive"
need_dir  orbis-compat/include      "and it must be -isystem'd AHEAD of sdk/include"
need_file orbis-compat/include/orbis_prefix.h    "the -include prefix that replaces -include stdlib.h"
need_file orbis-compat/scripts/ps4/make-pkg.sh   "packaging"
need_file mesa/manifest.txt         "the primary record of which orbis-compat Mesa saw"
need_dir  mesa/include/vulkan       "the headers RADV was built against - a mismatched copy is a struct-layout bug that compiles cleanly"
need_file mesa/build-orbis/src/amd/vulkan/libvulkan_radeon.a "RADV"
need_file mesa/build-orbis/src/egl/libEGL.a "EGL"
need_file NOTICE.md                 "the notices that must travel with the binaries"
need_file LICENSING.md              "the per-component argument behind them"
need_dir  licenses                  "the actual licence texts"
for g in "mesa/build-orbis/src/gallium/targets/dri/libgallium-*.a" "mesa/build-orbis/subprojects/zlib-*/libz.a"; do
  # Both are found by GLOB in every consumer (the Makefile, gllinkprobe.sh, the composite
  # action), because the gallium archive is version-stamped. Check them the same way.
  # shellcheck disable=SC2086
  found=$(cd "$B" && ls $g 2>/dev/null | head -1)
  [ -n "$found" ] && ok "$found" || { err "MISSING $g"; RC=1; }
done

# ⚠ toolchain/orbis-tls.ld AND orbis-compat/cmake/orbis-tls.ld are BOTH in the bundle and they
# must be the same bytes. The meson cross file names the second (it substitutes @ORBIS_COMPAT@)
# and the CMake path names the first; two copies that drifted would mean a meson build and a
# CMake build of the same source linking with different linker scripts, and the symptom of that
# is the console rejecting an image for "segment #1 is not page aligned" - visible nowhere else.
if [ -f "$B/toolchain/orbis-tls.ld" ] && [ -f "$B/orbis-compat/cmake/orbis-tls.ld" ]; then
  if cmp -s "$B/toolchain/orbis-tls.ld" "$B/orbis-compat/cmake/orbis-tls.ld"; then
    ok "the two orbis-tls.ld copies are byte-identical"
  else
    err "toolchain/orbis-tls.ld and orbis-compat/cmake/orbis-tls.ld DIFFER. A meson build and a
   CMake build of the same source would link with different linker scripts."
    RC=1
  fi
fi

# ⚠ sdk/bin is checked as a WARNING, not a failure: a bundle cut with --bin-hosts for one
# host is a legitimate bundle that compiles and cannot package.
if [ -d "$B/sdk/bin/linux" ] || [ -d "$B/sdk/bin/macos" ]; then
  ok "sdk/bin: $(cd "$B/sdk/bin" && echo *)"
else
  warn "no sdk/bin/<host> - this bundle can compile but not package"
fi

# -----------------------------------------------------------------------------------------
log "the publication gate"
GATE="$(field gate)"
case "$GATE" in
  pass) ok "gate=pass - something has been built from an unpacked copy of this bundle" ;;
  *)    warn "gate=$GATE. NOTHING HAS BEEN BUILT FROM THIS BUNDLE. It is not publishable."
        warn "  Run: scripts/release/bundle-gate.sh <this bundle>   (needs ld.lld, llvm-ar, llvm-nm)"
        INCOMPLETE=1 ;;
esac

echo
if [ "$RC" -ne 0 ]; then
  err "FAILED - do not publish this bundle"
  exit 1
fi
if [ "$INCOMPLETE" -ne 0 ]; then
  warn "INCOMPLETE - every check that ran passed, but not every check ran."
  warn "  An incomplete verify is not a pass. See the lines marked !! above."
  exit 4
fi
log "OK - every check ran and every check passed"
